### ISSUE TITLE
gitignored directory

### ISSUE THREAD

**Issue by szepeviktor** [gnk-softworks/narvik#14]
Somehow `node_module` got into the repository.
https://github.com/gnk-softworks/narvik/tree/main/node_modules

This is how to check: `git ls-files --cached --ignored --exclude-standard`

[_source_](https://github.com/szepeviktor/byte-level-care/blob/bf6f463db210e3faf60df8262d94d9b4dd140195/.github/workflows/reusable-integrity.yml#L176)

**Comment by szepeviktor** [comment]
And `/.idea` also.

**Comment by Kawba** [comment]
This has already been fixed in the next branch and will be merged into main for next release.

**Comment by szepeviktor** [comment]
All right.
Please consider adding a PR template or set `next` as default branch to tell contributors where to work.

**Comment by szepeviktor** [comment]
https://narvik-auth.com/contributing/
